name: "Staged dependencies action"
description: "Github Actions to implement R development stages for package development"
inputs:
  path:
    description: Path to package's root
    required: false
    default: "."
  new-package:
    description: ""
    required: false
    default: false
  no-check-dependencies:
    description: ""
    required: false
    default: false
  no-check-deprecated:
    description: ""
    required: false
    default: false
  no-check-remotes:
    description: ""
    required: false
    default: false
  no-check-version-num:
    description: ""
    required: false
    default: false
  no-check-R-ver:
    description: ""
    required: false
    default: false
  no-check-pkg-size:
    description: ""
    required: false
    default: false
  no-check-file-size:
    description: ""
    required: false
    default: false
  no-check-bioc-views:
    description: ""
    required: false
    default: false
  no-check-bbs:
    description: ""
    required: false
    default: false
  no-check-description:
    description: ""
    required: false
    default: false
  no-check-namespace:
    description: ""
    required: false
    default: false
  no-check-vignettes:
    description: ""
    required: false
    default: false
  no-check-library-calls:
    description: ""
    required: false
    default: false
  no-check-install-self:
    description: ""
    required: false
    default: false
  no-check-coding-practices:
    description: ""
    required: false
    default: false
  no-check-function-len:
    description: ""
    required: false
    default: false
  no-check-man-doc:
    description: ""
    required: false
    default: false
  no-check-news:
    description: ""
    required: false
    default: false
  no-check-unit-tests:
    description: ""
    required: false
    default: false
  no-check-skip-bioc-tests:
    description: ""
    required: false
    default: false
  no-check-formatting:
    description: ""
    required: false
    default: false
  no-check-CRAN:
    description: ""
    required: false
    default: false
  no-check-bioc-help:
    description: ""
    required: false
    default: false
  build-output-file:
    description: ""
    required: false
  quit-with-status:
    description: ""
    required: false
    default: false
  cache-version:
    description: ""
    required: false
    default: "cache-v1"

branding:
  icon: 'arrow-down'
  color: 'blue'
runs:
  using: "composite"
  steps:
      - name: Set R Library home on Linux
        if: runner.os == 'Linux'
        run: |
          mkdir /__w/_temp/Library
          echo ".libPaths('/__w/_temp/Library')" > ~/.Rprofile
        shell: bash

      - name: Cache R packages
        if: "!contains(github.event.head_commit.message, '/nocache')"
        uses: actions/cache@v2
        with:
          path: /home/runner/work/_temp/Library
          key: ${{ inputs.cache-version }}-${{ runner.os }}-biocversion-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ inputs.cache-version }}-${{ runner.os }}-biocversion

      - name: Install dependencies
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org/"))
          ncores <- parallel::detectCores(all.tests = FALSE, logical = TRUE)
          if (!require("BiocManager")) install.packages("BiocManager", upgrade = "never", Ncpus = ncores)
          BiocManager::install("BiocCheck", update = FALSE, ask = FALSE)
        shell: Rscript {0}

      - name: Prepare script options
        run: |
          declare -a options
          test ${NEW_PACKAGE} && options+=(--new-package)
          test ${NO_CHECK_DEPENDENCIES} && options+=(--no-check-dependencies)
          test ${NO_CHECK_DEPRECATED} && options+=(--no-check-deprecated)
          test ${NO_CHECK_REMOTES} && options+=(--no-check-remotes)
          test ${NO_CHECK_VERSION_NUM} && options+=(--no-check-version-num)
          test ${NO_CHECK_R_VER} && options+=(--no-check-R-ver)
          test ${NO_CHECK_PKG_SIZE} && options+=(--no-check-pkg-size)
          test ${NO_CHECK_FILE_SIZE} && options+=(--no-check-file-size)
          test ${NO_CHECK_BIOC_VIEWS} && options+=(--no-check-bioc-views)
          test ${NO_CHECK_BBS} && options+=(--no-check-bbs)
          test ${NO_CHECK_DESCRIPTION} && options+=(--no-check-description)
          test ${NO_CHECK_NAMESPACE} && options+=(--no-check-namespace)
          test ${NO_CHECK_VIGNETTES} && options+=(--no-check-vignettes)
          test ${NO_CHECK_LIBRARY_CALLS} && options+=(--no-check-library-calls)
          test ${NO_CHECK_INSTALL_SELF} && options+=(--no-check-install-self)
          test ${NO_CHECK_CODING_PRACTICES} && options+=(--no-check-coding-practices)
          test ${NO_CHECK_FUNCTION_LEN} && options+=(--no-check-function-len)
          test ${NO_CHECK_MAN_DOC} && options+=(--no-check-man-doc)
          test ${NO_CHECK_NEWS} && options+=(--no-check-news)
          test ${NO_CHECK_UNIT_TESTS} && options+=(--no-check-unit-tests)
          test ${NO_CHECK_SKIP_BIOC_TESTS} && options+=(--no-check-skip-bioc-tests)
          test ${NO_CHECK_FORMATTING} && options+=(--no-check-formatting)
          test ${NO_CHECK_CRAN} && options+=(--no-check-CRAN)
          test ${NO_CHECK_BIOC_HELP} && options+=(--no-check-bioc-help)
          test ${BUILD_OUTPUT_FILE} && options+=(--build-output-file ${BUILD_OUTPUT_FILE})
          test ${QUIT_WITH_STATUS} && options+=(--quit-with-status)
          echo "BIOC_OPTIONS=${options[@]}" >> $GITHUB_ENV
        shell: bash

      - name: Run BiocCheck
        run: |
          echo -e "Running: ${GITHUB_ACTION_PATH}/BiocCheck.R ${BIOC_OPTIONS} ${{ inputs.path }}\n\n"
          ${GITHUB_ACTION_PATH}/BiocCheck.R ${BIOC_OPTIONS} ${{ inputs.path }}
        shell: bash
