---
name: Staged dependencies action test

on:
  push:
    tags:
      - "v*"
    branches:
      - main
      - pre-release
  pull_request:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    name: ${{ matrix.image }}, version ${{ matrix.tag }}
    container:
      image: ${{ matrix.image }}:${{ matrix.tag }}
    strategy:
      fail-fast: false
      matrix:
        image: ["rocker/verse"]
        tag: ["4.1.0",]
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Checkout test repo
        uses: actions/checkout@v2
        with:
          repository: "openpharma/stageddeps.elecinfra"
          path: "stageddeps.elecinfra"

      - name: Run r cmd check
        run: |
          R CMD build stageddeps.elecinfra
          R CMD INSTALL stageddeps.elecinfra_*.tar.gz
          R CMD check stageddeps.elecinfra_*.tar.gz

      - name: Test bioccheck action
        uses: ./
        with:
          path: "stageddeps.elecinfra"
          no-check-bioc-help: true
          no-check-man-doc: true
          no-check-vignettes: true
          no-check-bioc-views: true
          no-cache: true
